# Generated by Django 3.2.20 on 2023-11-19 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='agencies')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('icon', models.ImageField(blank=True, default=None, upload_to='categories')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default=None, upload_to='reporters')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('token', models.CharField(max_length=12, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news')),
                ('description', models.TextField()),
                ('is_draft', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.agency')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.reporter')),
                ('categories', models.ManyToManyField(blank=True, to='news.Category')),
            ],
        ),
    ]
