# Generated by Django 3.2.20 on 2023-11-20 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_agency_category_news_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='agencies'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.reporter'),
        ),
        migrations.AlterField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(blank=True, default=None, to='news.Category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='news'),
        ),
    ]
