# Generated by Django 3.2.20 on 2023-11-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20231120_1819'),
        ('news', '0003_auto_20231121_1559'),
    ]

    operations = [
    ]
