# Generated by Django 3.2.20 on 2023-11-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20231120_1819'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='user',
            new_name='subscriber',
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('subscriber', 'news')},
        ),
    ]
