# Generated by Django 3.2.20 on 2023-11-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_merge_0003_auto_20231120_1819_0003_auto_20231121_1559'),
        ('feedback', '0004_comment_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.AddField(
            model_name='comment',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.subscriber'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('LIKE', 'LIKE'), ('DISLIKE', 'DISLIKE')], max_length=7),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.subscriber'),
        ),
    ]
