# Generated by Django 3.2.20 on 2023-11-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20231125_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='reaction',
            new_name='reactionType',
        ),
    ]
